<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Johanna Enright">

<title>Investigating the Efficacy of a Novel Peptide in Inhibiting a Key Antibiotic Resistance Enzyme in Escherichia coli</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Assignment6_markdown_JohannaEnright_files/libs/clipboard/clipboard.min.js"></script>
<script src="Assignment6_markdown_JohannaEnright_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Assignment6_markdown_JohannaEnright_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Assignment6_markdown_JohannaEnright_files/libs/quarto-html/popper.min.js"></script>
<script src="Assignment6_markdown_JohannaEnright_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Assignment6_markdown_JohannaEnright_files/libs/quarto-html/anchor.min.js"></script>
<link href="Assignment6_markdown_JohannaEnright_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Assignment6_markdown_JohannaEnright_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Assignment6_markdown_JohannaEnright_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Assignment6_markdown_JohannaEnright_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Assignment6_markdown_JohannaEnright_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Investigating the Efficacy of a Novel Peptide in Inhibiting a Key Antibiotic Resistance Enzyme in <em>Escherichia coli</em></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Johanna Enright </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/peptide.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:4in"></p>
</figure>
</div>
<section id="background-information" class="level2">
<h2 class="anchored" data-anchor-id="background-information">Background information</h2>
<p>My data looks at <em>Escherichia coli</em> growth over a 24h period in a 96-well plate when treated with 2 drugs: ampicillin and a novel 14-amino acid peptide. The plate will have increasing concentration gradients of each drug along the x and y axis, respectively, along with an inoculum of bacteria (1 strain per plate) in each well.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/checkerboard_setup.png" class="img-fluid figure-img"></p>
<figcaption>Figure 1. Checkerboard assay setup</figcaption>
</figure>
</div>
<p>The <em>E.coli</em> test strain contains an plasmid borne enzyme (TEM-1) that confers resistance to ampicillin. The novel peptide is proven to bind to and inhibit TEM-1 <em>in-vitro</em>, so we are seeing if it can also inhibit TEM-1 in bacterial cells.</p>
<p>For the test strain (<em>E.coli</em> PB9) which contains TEM-1, we are hoping to see that ampicillin’s efficacy is restored with the addition of our peptide. If the peptide inhibits TEM-1, then TEM-1 is not available to degrade ampicillin, so ampicillin is able to enact its bactericidal effect by targeting a key enzyme in the bacterial cell wall.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/peptide_mechanism_of_action.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2. Proposed effect of peptide and ampicillin on key cell wall enzyme (PBP) in gram-negative bacteria.</figcaption>
</figure>
</div>
<p>Ideally, we hope to see that with increasing peptide concentrations, the amount of ampicillin required to kill the bacteria decreases. Additionally, there will be a control <em>E.coli</em> strain which does not contain TEM-1. For this strain, we would expect to see only a response in growth to ampicillin and not peptide. It’s growth across the plate should only change vertically with ampicillin concentration, and not horizontally with the peptide because it does not contain TEM-1 (the enzyme that we hope the peptide inhibits) so it is more susceptible to ampicillin. We will ultimately compare the growth patterns of the TEM-1 containing PB9 strain to that of the MG1655 control.</p>
</section>
<section id="questions-i-hope-to-answer-in-my-analysis" class="level2">
<h2 class="anchored" data-anchor-id="questions-i-hope-to-answer-in-my-analysis">Questions I hope to answer in my analysis:</h2>
<ul>
<li>does growth decrease with increasing ampicillin concentration?</li>
<li>does growth decrease with increasing peptide concentration?</li>
<li>do peptide and ampicillin together lower the amount of ampicillin that is required to inhibit bacterial growth?</li>
<li>is this change in decreased growth noticeable and different from the control?</li>
</ul>
</section>
<section id="analysis-of-data" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-data">Analysis of data</h2>
<section id="loading-packages-for-analysis" class="level4">
<h4 class="anchored" data-anchor-id="loading-packages-for-analysis">Loading packages for analysis</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="reading-in-e.coli-pb9-growth-curve-data-cleaning-wrangling-it." class="level4">
<h4 class="anchored" data-anchor-id="reading-in-e.coli-pb9-growth-curve-data-cleaning-wrangling-it.">Reading in <em>E.coli</em> PB9 growth curve data &amp; cleaning &amp; wrangling it.</h4>
<p>This data comes in the format with time, temperature and well columns. The well columns contain the OD600 (absorbance at 600nm wavelength) at each time point for each well.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>OD_time_info <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"growthcurvedata/checkerboard_PB9_amp_EP6_250219_input.csv"</span>, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">show_col_types =</span> F) </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(OD_time_info, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 98
  Time     `T° 600`    A1    A2    A3    A4    A5    A6    A7    A8    A9   A10
  &lt;time&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 00:00:22     26   0.094 0.092 0.093 0.582 0.106 0.099 0.101 0.187 0.102 0.593
2 00:30:22     36.9 0.094 0.092 0.092 0.096 0.098 0.094 0.095 0.096 0.097 0.097
3 01:00:22     37   0.094 0.092 0.092 0.096 0.098 0.095 0.095 0.096 0.098 0.098
# ℹ 86 more variables: A11 &lt;dbl&gt;, A12 &lt;dbl&gt;, B1 &lt;dbl&gt;, B2 &lt;dbl&gt;, B3 &lt;dbl&gt;,
#   B4 &lt;dbl&gt;, B5 &lt;dbl&gt;, B6 &lt;dbl&gt;, B7 &lt;dbl&gt;, B8 &lt;dbl&gt;, B9 &lt;dbl&gt;, B10 &lt;dbl&gt;,
#   B11 &lt;dbl&gt;, B12 &lt;dbl&gt;, C1 &lt;dbl&gt;, C2 &lt;dbl&gt;, C3 &lt;dbl&gt;, C4 &lt;dbl&gt;, C5 &lt;dbl&gt;,
#   C6 &lt;dbl&gt;, C7 &lt;dbl&gt;, C8 &lt;dbl&gt;, C9 &lt;dbl&gt;, C10 &lt;dbl&gt;, C11 &lt;dbl&gt;, C12 &lt;dbl&gt;,
#   D1 &lt;dbl&gt;, D2 &lt;dbl&gt;, D3 &lt;dbl&gt;, D4 &lt;dbl&gt;, D5 &lt;dbl&gt;, D6 &lt;dbl&gt;, D7 &lt;dbl&gt;,
#   D8 &lt;dbl&gt;, D9 &lt;dbl&gt;, D10 &lt;dbl&gt;, D11 &lt;dbl&gt;, D12 &lt;dbl&gt;, E1 &lt;dbl&gt;, E2 &lt;dbl&gt;,
#   E3 &lt;dbl&gt;, E4 &lt;dbl&gt;, E5 &lt;dbl&gt;, E6 &lt;dbl&gt;, E7 &lt;dbl&gt;, E8 &lt;dbl&gt;, E9 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(OD_time_info)  <span class="co">#there are time, temperature, and well columns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Time"   "T° 600" "A1"     "A2"     "A3"     "A4"     "A5"     "A6"    
 [9] "A7"     "A8"     "A9"     "A10"    "A11"    "A12"    "B1"     "B2"    
[17] "B3"     "B4"     "B5"     "B6"     "B7"     "B8"     "B9"     "B10"   
[25] "B11"    "B12"    "C1"     "C2"     "C3"     "C4"     "C5"     "C6"    
[33] "C7"     "C8"     "C9"     "C10"    "C11"    "C12"    "D1"     "D2"    
[41] "D3"     "D4"     "D5"     "D6"     "D7"     "D8"     "D9"     "D10"   
[49] "D11"    "D12"    "E1"     "E2"     "E3"     "E4"     "E5"     "E6"    
[57] "E7"     "E8"     "E9"     "E10"    "E11"    "E12"    "F1"     "F2"    
[65] "F3"     "F4"     "F5"     "F6"     "F7"     "F8"     "F9"     "F10"   
[73] "F11"    "F12"    "G1"     "G2"     "G3"     "G4"     "G5"     "G6"    
[81] "G7"     "G8"     "G9"     "G10"    "G11"    "G12"    "H1"     "H2"    
[89] "H3"     "H4"     "H5"     "H6"     "H7"     "H8"     "H9"     "H10"   
[97] "H11"    "H12"   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(OD_time_info<span class="sc">$</span>Time)  <span class="co">#Time column: time is given as hours:minutes:seconds</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>00:00:22
00:30:22
01:00:22
01:30:22
02:00:22
02:30:22</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(OD_time_info<span class="sc">$</span>Time) <span class="co">#starts at 22 seconds</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time difference of 22 secs</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(OD_time_info<span class="sc">$</span>Time <span class="sc">/</span> <span class="dv">3600</span>) <span class="co">#ends at 24h and 22s</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time difference of 24.00611 secs</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Note: the times are in time differences and not numeric.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(OD_time_info<span class="sc">$</span>Time) <span class="co">#49 time readings (every 30min for 24h) as expected.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 49</code></pre>
</div>
</div>
<p><strong>Make new time column containing just the time in hours as a decimal:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>makenewtime <span class="ot">&lt;-</span> <span class="cf">function</span>(df){</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(df, <span class="at">newtime =</span> (<span class="fu">as.numeric</span>(df<span class="sc">$</span>Time) <span class="sc">-</span> df<span class="sc">$</span>Time[<span class="dv">1</span>]) <span class="sc">/</span> <span class="dv">3600</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>newtime <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(df<span class="sc">$</span>newtime)  <span class="co">#recognized as a number, not a time in seconds</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#subtract the seconds because this will change slightly from plate to plate, depending on  how long the plate is shaken for (15 or 20s). Also divide by 3600s/h</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>OD_time_info <span class="ot">&lt;-</span> <span class="fu">makenewtime</span>(OD_time_info) <span class="co">#column added</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(OD_time_info<span class="sc">$</span>newtime)   <span class="co">#looks good.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  0.0  0.5  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0
[16]  7.5  8.0  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5
[31] 15.0 15.5 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0
[46] 22.5 23.0 23.5 24.0</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(OD_time_info<span class="sc">$</span>newtime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
</div>
<p>I will remove the temperature column which gives the temperature of the plate reader at each reading. This data will not be used.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>OD_time_info <span class="ot">&lt;-</span> OD_time_info[,<span class="sc">-</span><span class="dv">2</span>]  <span class="co">#removing Temp column from data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Now looking at the well columns.</strong> These are represented as a column for each well from 0 to 24h (NOT TIDY!). Each column contains an OD600 reading.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>OD_time_info[,<span class="dv">2</span><span class="sc">:</span><span class="fu">ncol</span>(OD_time_info)] <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">3</span>) <span class="co">#each column contains an OD600 reading</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 97
     A1    A2    A3    A4    A5    A6    A7    A8    A9   A10   A11   A12    B1
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 0.094 0.092 0.093 0.582 0.106 0.099 0.101 0.187 0.102 0.593 0.128 0.114 0.093
2 0.094 0.092 0.092 0.096 0.098 0.094 0.095 0.096 0.097 0.097 0.101 0.104 0.097
3 0.094 0.092 0.092 0.096 0.098 0.095 0.095 0.096 0.098 0.098 0.101 0.103 0.098
# ℹ 84 more variables: B2 &lt;dbl&gt;, B3 &lt;dbl&gt;, B4 &lt;dbl&gt;, B5 &lt;dbl&gt;, B6 &lt;dbl&gt;,
#   B7 &lt;dbl&gt;, B8 &lt;dbl&gt;, B9 &lt;dbl&gt;, B10 &lt;dbl&gt;, B11 &lt;dbl&gt;, B12 &lt;dbl&gt;, C1 &lt;dbl&gt;,
#   C2 &lt;dbl&gt;, C3 &lt;dbl&gt;, C4 &lt;dbl&gt;, C5 &lt;dbl&gt;, C6 &lt;dbl&gt;, C7 &lt;dbl&gt;, C8 &lt;dbl&gt;,
#   C9 &lt;dbl&gt;, C10 &lt;dbl&gt;, C11 &lt;dbl&gt;, C12 &lt;dbl&gt;, D1 &lt;dbl&gt;, D2 &lt;dbl&gt;, D3 &lt;dbl&gt;,
#   D4 &lt;dbl&gt;, D5 &lt;dbl&gt;, D6 &lt;dbl&gt;, D7 &lt;dbl&gt;, D8 &lt;dbl&gt;, D9 &lt;dbl&gt;, D10 &lt;dbl&gt;,
#   D11 &lt;dbl&gt;, D12 &lt;dbl&gt;, E1 &lt;dbl&gt;, E2 &lt;dbl&gt;, E3 &lt;dbl&gt;, E4 &lt;dbl&gt;, E5 &lt;dbl&gt;,
#   E6 &lt;dbl&gt;, E7 &lt;dbl&gt;, E8 &lt;dbl&gt;, E9 &lt;dbl&gt;, E10 &lt;dbl&gt;, E11 &lt;dbl&gt;, E12 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p><strong>Double checking that each column has 49 readings and no NAs:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>checklength_and_NAs <span class="ot">&lt;-</span> <span class="cf">function</span>(df){</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">97</span>){</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">#checking 49 readings</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">as.numeric</span>(<span class="fu">nrow</span>(df[,i]) <span class="sc">!=</span> <span class="dv">49</span>)){</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">print</span>(<span class="fu">paste</span>(</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"length of column"</span>, <span class="fu">names</span>(df[i]), <span class="st">"is not 49, it's"</span>, <span class="fu">nrow</span>(df[,i])))</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">#checking NAs</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">sum</span>(<span class="fu">is.na</span>(df[,i])) <span class="sc">!=</span> <span class="dv">0</span>){</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"column"</span>, <span class="fu">names</span>(df[i]), <span class="st">"has"</span>, <span class="fu">sum</span>(<span class="fu">is.na</span>(df[,i])), <span class="st">"NAs"</span>))</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="fu">checklength_and_NAs</span>(OD_time_info)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="co">#if nothing prints there are no problems.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>looks good.</p>
<p><strong>Now convert table to long format.</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#convert to long format</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>pivotlong_gc <span class="ot">&lt;-</span> <span class="cf">function</span>(df){</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(df, <span class="at">cols =</span> A1<span class="sc">:</span>H12, </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">names_to =</span> <span class="st">"well"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">values_to =</span> <span class="st">"OD600"</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(df <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">3</span>))</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"nrow: "</span>, <span class="fu">nrow</span>(df)))  <span class="co">#this is good because 96 * 49 = 4704</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>long_OD_time_info <span class="ot">&lt;-</span> <span class="fu">pivotlong_gc</span>(OD_time_info)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Time   newtime well  OD600
  &lt;time&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
1 00'22"       0 A1    0.094
2 00'22"       0 A2    0.092
3 00'22"       0 A3    0.093
[1] "nrow:  4704"</code></pre>
</div>
</div>
<p><strong>Now Checking that there are no weird OD values:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>distributionOD <span class="ot">&lt;-</span> <span class="cf">function</span>(df, title){</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a> plot <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> OD600)) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"#043927"</span>, <span class="at">bins =</span> <span class="dv">40</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">labs</span>(<span class="at">title =</span> title) <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">theme_light</span>()</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a> <span class="fu">return</span>(plot)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="fu">distributionOD</span>(long_OD_time_info, <span class="st">"Distribution of OD600 well readings for a 24h E.coli growth curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment6_markdown_JohannaEnright_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This is good. OD readings should be above 0, and not too far above 1. Also having a lot of readings near 0 makes sense as not all wells will have growth and also many wells before the 10ish hour mark will have very minimal growth.</p>
<p><strong>Now add 2 new columns: ‘column’ and ‘row’ which will be used later for graphing.</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>addcolumnrow <span class="ot">&lt;-</span> <span class="cf">function</span>(df){</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(df, <span class="at">row =</span> <span class="fu">substr</span>(df<span class="sc">$</span>well, <span class="at">start =</span> <span class="dv">1</span>, <span class="at">stop =</span> <span class="dv">1</span>),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">column =</span> <span class="fu">substr</span>(df<span class="sc">$</span>well, <span class="at">start =</span> <span class="dv">2</span>, <span class="at">stop =</span> <span class="fu">length</span>(df<span class="sc">$</span>well)) )</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#make it see column numbers as discrete variables (not contiuous), needed for graphing</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>column <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>column, <span class="at">levels =</span> df<span class="sc">$</span>column[<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>])  </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(df <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">3</span>)) <span class="co">#the 2 new columns are there</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>long_OD_time_info <span class="ot">&lt;-</span> <span class="fu">addcolumnrow</span>(long_OD_time_info)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  Time   newtime well  OD600 row   column
  &lt;time&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;fct&gt; 
1 00'22"       0 A1    0.094 A     1     
2 00'22"       0 A2    0.092 A     2     
3 00'22"       0 A3    0.093 A     3     </code></pre>
</div>
</div>
<p>looks good.</p>
<p><strong>Reading in drug concentration data</strong></p>
<p>Now I need to read in a new file ‘PB9_drugconcs.csv’. This gives the ampicillin and peptide concentration used for each row or column (respectively) for this checkerboard. This information will need to be wrangled so it can be added to the PB9 growth curve data.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>drugconcs <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"drugconcs/PB9_drugconcs.csv"</span>, <span class="at">show_col_types =</span> F)  </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(drugconcs, <span class="dv">3</span>) <span class="co">#values in uM or ug/mL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  ampconc_ugml pepconc_ugml ampconc_uM pepconc_uM
         &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
1            0            0          0        0  
2          300            4        808        2.5
3          500            9       1346        5  </code></pre>
</div>
</div>
<p>We only need the <span class="math inline">\(\mu M\)</span> columns, so <span class="math inline">\(\mu g/mL\)</span> will be removed. We do not need to remove NAs because there are only 8 ampicillin rows which will be indexed for accordingly.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>drugconcs <span class="ot">&lt;-</span> <span class="fu">select</span>(drugconcs, ampconc_uM, pepconc_uM) <span class="co">#remove ug/mL</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(drugconcs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   ampconc_uM pepconc_uM
        &lt;dbl&gt;      &lt;dbl&gt;
 1          0        0  
 2        808        2.5
 3       1346        5  
 4       1885       10  
 5       2423       15  
 6       2962       20  
 7       3500       25  
 8       4039       30  
 9         NA       40  
10         NA       50  
11         NA       60  
12         NA       70  </code></pre>
</div>
</div>
<p>Now we will add these drug concentration values to their respective rows / columns in the original dataframe.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>adddrugconcs <span class="ot">&lt;-</span> <span class="cf">function</span>(dfgc, dfdc){</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>         dfgc <span class="ot">&lt;-</span> dfgc <span class="sc">%&gt;%</span>  <span class="fu">mutate</span>(<span class="at">amp_uM =</span> <span class="fu">case_when</span>(</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                            dfgc<span class="sc">$</span>row <span class="sc">==</span> <span class="st">"A"</span> <span class="sc">~</span> dfdc<span class="sc">$</span>ampconc_uM[<span class="dv">1</span>],</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                            dfgc<span class="sc">$</span>row <span class="sc">==</span> <span class="st">"B"</span> <span class="sc">~</span> dfdc<span class="sc">$</span>ampconc_uM[<span class="dv">2</span>],</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                            dfgc<span class="sc">$</span>row <span class="sc">==</span> <span class="st">"C"</span> <span class="sc">~</span> dfdc<span class="sc">$</span>ampconc_uM[<span class="dv">3</span>],</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                            dfgc<span class="sc">$</span>row <span class="sc">==</span> <span class="st">"D"</span> <span class="sc">~</span> dfdc<span class="sc">$</span>ampconc_uM[<span class="dv">4</span>],</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>                            dfgc<span class="sc">$</span>row <span class="sc">==</span> <span class="st">"E"</span> <span class="sc">~</span> dfdc<span class="sc">$</span>ampconc_uM[<span class="dv">5</span>],</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>                            dfgc<span class="sc">$</span>row <span class="sc">==</span> <span class="st">"F"</span> <span class="sc">~</span> dfdc<span class="sc">$</span>ampconc_uM[<span class="dv">6</span>],</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>                            dfgc<span class="sc">$</span>row <span class="sc">==</span> <span class="st">"G"</span> <span class="sc">~</span> dfdc<span class="sc">$</span>ampconc_uM[<span class="dv">7</span>],</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>                            dfgc<span class="sc">$</span>row <span class="sc">==</span> <span class="st">"H"</span> <span class="sc">~</span> dfdc<span class="sc">$</span>ampconc_uM[<span class="dv">8</span>]),</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">pep_uM =</span> <span class="fu">case_when</span>(dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">1</span>],</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>                             dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">2</span>],</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>                             dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">3</span>],</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>                             dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">4</span>],</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>                             dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">5</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">5</span>],</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>                             dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">6</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">6</span>],</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>                             dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">7</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">7</span>],</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>                             dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">8</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">8</span>],</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>                             dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">9</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">9</span>],</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>                             dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">10</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">10</span>],</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>                             dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">11</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">11</span>],</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>                             dfgc<span class="sc">$</span>column <span class="sc">==</span> <span class="dv">12</span> <span class="sc">~</span> dfdc<span class="sc">$</span>pepconc_uM[<span class="dv">12</span>])</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>       )</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>    <span class="co">#make these concentrations factors, so the graphs will work properly later!</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>    <span class="co">#(discrete values!)</span></span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>    dfgc<span class="sc">$</span>amp_uM   <span class="ot">&lt;-</span> <span class="fu">factor</span>(dfgc<span class="sc">$</span>amp_uM, <span class="at">levels =</span> dfgc<span class="sc">$</span>amp_uM[<span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">96</span>, <span class="at">by=</span><span class="dv">12</span>)])</span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a>    dfgc<span class="sc">$</span>pep_uM   <span class="ot">&lt;-</span> <span class="fu">factor</span>(dfgc<span class="sc">$</span>pep_uM, <span class="at">levels =</span> <span class="fu">na.omit</span>(dfgc<span class="sc">$</span>pep_uM[<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>]))       </span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(dfgc <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">3</span>))</span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(dfgc)</span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a>long_OD_time_info <span class="ot">&lt;-</span> <span class="fu">adddrugconcs</span>(long_OD_time_info, drugconcs)   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 8
  Time   newtime well  OD600 row   column amp_uM pep_uM
  &lt;time&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt;  &lt;fct&gt; 
1 00'22"       0 A1    0.094 A     1      0      0     
2 00'22"       0 A2    0.092 A     2      0      2.5   
3 00'22"       0 A3    0.093 A     3      0      5     </code></pre>
</div>
</div>
<p>It looks like the new columns have been added!</p>
<p><strong>Reading in background absorbance value data and wrangling</strong></p>
<p>Now we will read in the background OD600 data from a separate csv file. This is a single time OD600 reading plate with only media in it. It needs to be subtracted as background absorbance values from the growth curve data.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>bgOD <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"background/camhb_bg_input.csv"</span>, <span class="at">show_col_types =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...1`</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bgOD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  ...1    `1`   `2`   `3`   `4`   `5`   `6`   `7`   `8`   `9`  `10`  `11`  `12`
  &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 A     0.092 0.093 0.094 0.095 0.094 0.093 0.093 0.092 0.092 0.093 0.092 0.093
2 B     0.092 0.093 0.093 0.094 0.094 0.093 0.092 0.092 0.092 0.091 0.091 0.091
3 C     0.093 0.092 0.093 0.093 0.092 0.092 0.092 0.092 0.092 0.092 0.092 0.092
4 D     0.093 0.092 0.094 0.093 0.093 0.093 0.092 0.092 0.092 0.093 0.092 0.092
5 E     0.093 0.092 0.093 0.092 0.092 0.091 0.091 0.092 0.092 0.093 0.092 0.092
6 F     0.092 0.092 0.093 0.092 0.091 0.093 0.091 0.091 0.091 0.092 0.091 0.092</code></pre>
</div>
</div>
<p>column names ‘…1’ needs to be fixed for clarity. The other columns probably shouldn’t have back ticks, but we won’t be working with this data for long, so it is not necessary to fix them.</p>
<p>Now I will fix the name of column 1 and format the table so that it is tidy and long format so it can be subtracted from growth curve data.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>bgOD <span class="ot">&lt;-</span> <span class="fu">rename</span>(bgOD, <span class="at">row =</span> ...<span class="dv">1</span>)   <span class="co">#fix name of column 1, rename it 'row'</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co">#use pivot longer, so this data can be used with above OD_time data</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>bgOD <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(bgOD, <span class="at">cols =</span> <span class="st">`</span><span class="at">1</span><span class="st">`</span><span class="sc">:</span><span class="st">`</span><span class="at">12</span><span class="st">`</span>,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">names_to =</span> <span class="st">"column"</span>,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">values_to =</span> <span class="st">"OD600"</span>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(bgOD, <span class="dv">3</span>))  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  row   column OD600
  &lt;chr&gt; &lt;chr&gt;  &lt;dbl&gt;
1 A     1      0.092
2 A     2      0.093
3 A     3      0.094</code></pre>
</div>
</div>
<p>looks good.</p>
<p>Add column ‘well’ so I can make sure the wells are in the same order as the growth curve data so that vectors line up before I subtract them.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>bgOD <span class="ot">&lt;-</span> <span class="fu">mutate</span>(bgOD, <span class="at">well =</span> <span class="fu">paste0</span>(row, column))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>bgOD[<span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">96</span>, <span class="at">by =</span> <span class="dv">12</span>),] <span class="co">#looks good.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
  row   column OD600 well 
  &lt;chr&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;
1 A     1      0.092 A1   
2 B     1      0.092 B1   
3 C     1      0.093 C1   
4 D     1      0.093 D1   
5 E     1      0.093 E1   
6 F     1      0.092 F1   
7 G     1      0.092 G1   
8 H     1      0.092 H1   </code></pre>
</div>
</div>
<p><strong>Double checking the range of OD600 values from the background data:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(bgOD<span class="sc">$</span>OD600)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.091 0.100</code></pre>
</div>
</div>
<p>It is good that the range is small because all wells just contain media, so they are the same and should contain little variation. 0.1 is quite low too which is what we expect as there is no bacterial growth in this media control plate.</p>
<p><strong>Checking the background and original growth curve data vectors align:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>long_OD_time_info<span class="sc">$</span>well[<span class="dv">1</span><span class="sc">:</span><span class="dv">96</span>] <span class="sc">==</span> bgOD<span class="sc">$</span>well  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[46] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[61] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[76] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[91] TRUE TRUE TRUE TRUE TRUE TRUE</code></pre>
</div>
</div>
<p>Yes, they do! This means they can be subtracted.</p>
<p>Now that we know the background wells and test plate wells are in the same order, I will subtract the background absorbance values from the original absorbance values in the growth curve data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>long_OD_time_info<span class="sc">$</span>OD600 <span class="ot">&lt;-</span> long_OD_time_info<span class="sc">$</span>OD600 <span class="sc">-</span> bgOD<span class="sc">$</span>OD600</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Checking that the range after subtraction is good:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(long_OD_time_info<span class="sc">$</span>OD600)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.008  1.426</code></pre>
</div>
</div>
<p>Once background is subtracted, OD is mostly above 0. Being slightly below 0 is okay as long as it’s not too far below, so all looks good here.</p>
</section>
<section id="initial-look-at-the-growth-curve-data" class="level4">
<h4 class="anchored" data-anchor-id="initial-look-at-the-growth-curve-data">Initial look at the growth curve data</h4>
<p><strong>Growth curves for control column and row</strong> First I will look at the control column and row (row 1 and column 1) which only have one drug type each. This will offer insight into how the bacteria is responding to each drug individually. We would expect lower growth in the ampicillin only column as ampicillin concentrations increase. We would also expect the same amount of growth in the peptide only row as peptide concentrations increase because the peptide is not beleived to be bactericidal on its own.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>rowAplot2 <span class="ot">&lt;-</span> long_OD_time_info <span class="sc">%&gt;%</span>     <span class="co">#testing plots on one row (row A)</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">filter</span>(row <span class="sc">==</span> <span class="st">"A"</span>) <span class="sc">%&gt;%</span>       </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> newtime, <span class="at">y =</span> OD600, <span class="at">color =</span> pep_uM)) <span class="sc">+</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time (hours)"</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">title =</span> <span class="st">"24h growth curve of E.coli PB9 </span><span class="sc">\n</span><span class="st">at ampicillin concentration 0 and varying peptide concs"</span>, </span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">color =</span> <span class="st">"Peptide </span><span class="sc">\n</span><span class="st">Conc. (\u00B5M)"</span>) <span class="sc">+</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>              <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>              <span class="fu">theme_minimal</span>()</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(rowAplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment6_markdown_JohannaEnright_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Another thing to note from these plots is that the OD reading often starts off high and drops within the first hour. This is likely due to condensation under the plate lid as the plate gets up to temperature. Also it could be from bubbles caused by the DMSO that the peptide is dissolved in. These generally pop over time when the plate is shaken every 30min. However this drop is kind of confusing to the overall trend, so going forward I will remove time points from the first hour, because they are not representative of actual bacterial growth.</p>
<p>When looking at the first row above. It appears as though the peptide on its own at higher concentrations is resulting in decreased bacteria growth. This is surprising, and suggests maybe the peptide does have some bactericidal effects on its own. Or perhaps some other unforeseen effect is at play.</p>
<p>Next, I will remove first hour points to test that this looks good and plot the control row (0 <span class="math inline">\(\mu M\)</span> peptide).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>makesinglerowplotpep <span class="ot">&lt;-</span> <span class="cf">function</span>(df, title){</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#no ampicillin row</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  p1 <span class="ot">&lt;-</span> df<span class="sc">%&gt;%</span> </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(amp_uM <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> newtime <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span>       </span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> newtime, <span class="at">y =</span> OD600, <span class="at">color =</span> pep_uM)) <span class="sc">+</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time (hours)"</span>, <span class="at">color =</span> <span class="st">"Peptide </span><span class="sc">\n</span><span class="st">Concentration (\u00B5M)"</span>,  <span class="at">title =</span> title) <span class="sc">+</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>()  <span class="sc">+</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(p1)</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="fu">makesinglerowplotpep</span>(long_OD_time_info, </span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>            <span class="st">"24h growth curve of E.coli PB9 </span><span class="sc">\n</span><span class="st">at ampicillin concentration 0"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment6_markdown_JohannaEnright_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>makesinglerowplotamp <span class="ot">&lt;-</span> <span class="cf">function</span>(df, title){</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co">#no peptide column</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  p2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(pep_uM <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> newtime <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span>       </span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> newtime, <span class="at">y =</span> OD600, <span class="at">color =</span> amp_uM)) <span class="sc">+</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time (hours)"</span>, </span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> <span class="st">"ampicillin </span><span class="sc">\n</span><span class="st">conc (\u00B5M)"</span>,</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> title) <span class="sc">+</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(p2)</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a><span class="fu">makesinglerowplotamp</span>(long_OD_time_info, </span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>            <span class="st">"24h growth curve of E.coli PB9 </span><span class="sc">\n</span><span class="st">at a peptide concentration of 0"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment6_markdown_JohannaEnright_files/figure-html/unnamed-chunk-22-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There is also definitely a decrease in bacterial growth with increasing ampicillin concentration. This makes sense, given that ampicillin is a bactericidal agent. Overall, the OD600 also appears to go down as peptide concentration increases.</p>
</section>
<section id="growth-curve-plots-for-whole-checkerboard" class="level4">
<h4 class="anchored" data-anchor-id="growth-curve-plots-for-whole-checkerboard">Growth Curve Plots for Whole Checkerboard</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>make_allwellgc <span class="ot">&lt;-</span> <span class="cf">function</span>(df, title){</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  allwellplot <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(newtime <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> newtime, <span class="at">y =</span> OD600)) <span class="sc">+</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_area</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Time (hours)"</span>, <span class="at">title =</span> title) <span class="sc">+</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_grid</span>(amp_uM <span class="sc">~</span> pep_uM, <span class="at">scales =</span> <span class="st">"fixed"</span>) <span class="sc">+</span> </span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">1.5</span>, <span class="fl">0.5</span>),</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>                       <span class="at">sec.axis =</span> <span class="fu">sec_axis</span>(<span class="sc">~</span> . ,</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">name =</span> <span class="st">"Ampicillin Concentration (\u00B5M)"</span>,</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">breaks =</span> <span class="cn">NULL</span>, <span class="at">labels =</span> <span class="cn">NULL</span>)) <span class="sc">+</span></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">24</span>, <span class="dv">4</span>), </span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>                       <span class="at">sec.axis =</span> <span class="fu">sec_axis</span>(<span class="sc">~</span> . , </span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">name =</span> <span class="st">"Peptide Concentration (\u00B5M)"</span>,</span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">breaks =</span> <span class="cn">NULL</span>, <span class="at">labels =</span> <span class="cn">NULL</span>)) <span class="sc">+</span></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb51-24"><a href="#cb51-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),  <span class="co"># Increase x-axis label</span></span>
<span id="cb51-25"><a href="#cb51-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),   <span class="co"># Increase y-axis label </span></span>
<span id="cb51-26"><a href="#cb51-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">4</span>),  <span class="co"># Increase x-axis scale values </span></span>
<span id="cb51-27"><a href="#cb51-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>),   <span class="co"># Increase y-axis scale values</span></span>
<span id="cb51-28"><a href="#cb51-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.title.y.right =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb51-29"><a href="#cb51-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">axis.title.x.top =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb51-30"><a href="#cb51-30" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.margin =</span> <span class="fu">unit</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="st">"cm"</span>)</span>
<span id="cb51-31"><a href="#cb51-31" aria-hidden="true" tabindex="-1"></a>    ) </span>
<span id="cb51-32"><a href="#cb51-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(allwellplot)</span>
<span id="cb51-33"><a href="#cb51-33" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb51-34"><a href="#cb51-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-35"><a href="#cb51-35" aria-hidden="true" tabindex="-1"></a>allwellplot <span class="ot">&lt;-</span> <span class="fu">make_allwellgc</span>(long_OD_time_info, <span class="st">"Growth curve of checkerboard assay for TEM-1 containing E.coli PB8"</span>)</span>
<span id="cb51-36"><a href="#cb51-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-37"><a href="#cb51-37" aria-hidden="true" tabindex="-1"></a><span class="co">#save plot to put image in quarto file t</span></span>
<span id="cb51-38"><a href="#cb51-38" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave2</span>(<span class="at">plot =</span> allwellplot,</span>
<span id="cb51-39"><a href="#cb51-39" aria-hidden="true" tabindex="-1"></a>        <span class="at">filename =</span> <span class="st">"plots/PB9_allwellplot.jpeg"</span>,</span>
<span id="cb51-40"><a href="#cb51-40" aria-hidden="true" tabindex="-1"></a>        <span class="at">width =</span> <span class="dv">24</span>, <span class="at">height =</span> <span class="dv">16</span>, <span class="at">units =</span> <span class="st">"cm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="plots/PB9_allwellplot.jpeg" class="img-fluid"> Overall, I think this is a promising sign that the peptide is working! As peptide increases, the general trend is lack of growth at lower ampicillin concentrations. For example at 0<span class="math inline">\(\mu M\)</span> peptide, 4039<span class="math inline">\(\mu M\)</span> of ampicillin is required to kill the bacteria. At 50 <span class="math inline">\(\mu M\)</span> of peptide, only 2423<span class="math inline">\(\mu M\)</span> of peptide is required to kill the bacteria. At 70<span class="math inline">\(\mu M\)</span> of peptide, only 808<span class="math inline">\(\mu M\)</span> of peptide is required to inhibit growth!</p>
<p>Additionally, it would appear that there is an increase in lag time of growth with increasing peptide concentrations. This means the peptide is still affecting growth even if it is not completely inhibiting it.</p>
</section>
<section id="calculating-the-area-under-the-curve-auc" class="level3">
<h3 class="anchored" data-anchor-id="calculating-the-area-under-the-curve-auc">Calculating the Area Under the Curve (AUC)</h3>
<p>Perhaps to account for factors like changes in lag time, we could use area under the curve (AUC) to quantify growth over time. I will now do some work to acquire the AUC and visualize it.</p>
<p><strong>A function to calculate the AUC.</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>calculatingarea <span class="ot">&lt;-</span> <span class="cf">function</span>(data, i){</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#use area of a trapezoid equation to determine area between 2 points, then sum them up</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  height <span class="ot">&lt;-</span> <span class="fu">lead</span>(data<span class="sc">$</span>newtime) <span class="sc">-</span> data<span class="sc">$</span>newtime</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  height <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(height)  <span class="co">#it was returning it as a difftime object</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  base1 <span class="ot">&lt;-</span> data<span class="sc">$</span>OD600</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  base2 <span class="ot">&lt;-</span> <span class="fu">lead</span>(data<span class="sc">$</span>OD600)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  Area <span class="ot">&lt;-</span> (base1 <span class="sc">+</span> base2)<span class="sc">*</span>height<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  Area <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(Area)</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">sum</span>(Area))</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Storing the AUCs in a vector for all 96 wells:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>wellnums <span class="ot">&lt;-</span> <span class="fu">unique</span>(long_OD_time_info<span class="sc">$</span>well)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>areavector <span class="ot">&lt;-</span> <span class="cf">function</span>(df){</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  allareas <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(<span class="fu">nrow</span>(df)<span class="sc">/</span><span class="dv">49</span>)) {</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>    A <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>           <span class="fu">filter</span>(well <span class="sc">==</span> wellnums[[i]]) <span class="sc">%&gt;%</span> </span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>           <span class="fu">calculatingarea</span>(i)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>    allareas <span class="ot">&lt;-</span> <span class="fu">c</span>(allareas, A)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">round</span>(allareas, <span class="dv">2</span>))</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>allareas <span class="ot">&lt;-</span> <span class="fu">areavector</span>(long_OD_time_info)</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(allareas[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 22.17 17.46 16.98 17.28 16.68 16.89 16.73 16.30 16.19 15.61</code></pre>
</div>
</div>
<p>Successfully calculated AUC.</p>
<p><strong>Adding the AUCs to the original data frame</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#now I will add the area data to the original data frame to do some work with it.</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>long_OD_time_info <span class="ot">&lt;-</span> long_OD_time_info <span class="sc">%&gt;%</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">mutate</span>(<span class="at">area =</span> <span class="fu">rep</span>(allareas, <span class="dv">49</span>)) </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co">#because area values correspond to the same order as well numbers, can just multiply them to match the same length. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Double checking… the same well for all time points should have the same area.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>long_OD_time_info <span class="sc">%&gt;%</span> </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(well <span class="sc">==</span> <span class="st">"A1"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(area) <span class="sc">%&gt;%</span> </span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">length</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>This looks good, the area for A1 for example at all time points is only has 1 AUC.</p>
<p><strong>Heatmap of AUC</strong></p>
<p>I will visualize this data using a heatmap to see if overall growth as represented by AUC is higher with lower drug concentrations and vise versa.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>makeheatmap <span class="ot">&lt;-</span> <span class="cf">function</span>(df, title){</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="co">#first I'm going to change the direction of the ampicillin factor, because I am used to visualizing checkerbaords with (0,0) in the top left corner.</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>amp_uM <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>amp_uM, <span class="at">levels =</span> <span class="fu">rev</span>(<span class="fu">unique</span>(df<span class="sc">$</span>amp_uM)))</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">%&gt;%</span> </span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> pep_uM, <span class="at">y =</span> amp_uM, <span class="at">fill =</span> area)) <span class="sc">+</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_discrete</span>(<span class="at">position =</span> <span class="st">"top"</span>) <span class="sc">+</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Peptide Concentration (\u00B5M)"</span>, </span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Ampicillin Concentration (\u00B5M)"</span>,</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">fill =</span> <span class="st">"Area"</span>,</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> title) <span class="sc">+</span></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(</span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.background =</span> <span class="fu">element_blank</span>(),  <span class="co">#this removes gray around the edges</span></span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.background  =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.border     =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>)</span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>PB9_hmap <span class="ot">&lt;-</span> <span class="fu">makeheatmap</span>(long_OD_time_info, </span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a>            <span class="at">title =</span> <span class="st">"Heatmap of area under the curve for each well in a Checkerboard </span><span class="sc">\n</span><span class="st">for TEM-1 ncontaining E.coli PB9"</span>)</span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a><span class="co">#PB9_hmap</span></span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a><span class="co">#saving image</span></span>
<span id="cb58-27"><a href="#cb58-27" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave2</span>(<span class="at">plot =</span> PB9_hmap, <span class="at">filename =</span> <span class="st">"plots/PB9_hmap.jpeg"</span>, <span class="at">width =</span> <span class="dv">12</span>, <span class="at">height =</span> <span class="dv">8</span>, <span class="at">units =</span> <span class="st">"cm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="plots/PB9_hmap.jpeg" class="img-fluid" style="width:8in"> This gives the same visual as the growth curve really. There is less curve area as concentrations for both drugs increase. Overall, this supports the same conclusion as above: that the peptide is effectively inhibiting TEM-1 allowing ampicillin to inhibit bacterial growth.</p>
<section id="comparison-of-pb9-data-to-control-mg1655-e.coli-strain." class="level4">
<h4 class="anchored" data-anchor-id="comparison-of-pb9-data-to-control-mg1655-e.coli-strain.">Comparison of PB9 data to control MG1655 <em>E.coli</em> Strain.</h4>
<p>Since a lot of the explanations for the data checking/wrangling have been done above, we will go faster for the control strain. Basically, for this checkerboard we want to see no response to peptide. Whereas for the above test strain we did want to see a response to peptide.</p>
<p><strong>Read in growth curve data for MG1655</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>MG1655_gc <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"./growthcurvedata/checkerboard_MG1655_amp_EP6_250123_input.csv"</span>, <span class="at">show_col_types =</span> F)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(MG1655_gc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Time"   "T° 600" "A1"     "A2"     "A3"     "A4"     "A5"     "A6"    
 [9] "A7"     "A8"     "A9"     "A10"    "A11"    "A12"    "B1"     "B2"    
[17] "B3"     "B4"     "B5"     "B6"     "B7"     "B8"     "B9"     "B10"   
[25] "B11"    "B12"    "C1"     "C2"     "C3"     "C4"     "C5"     "C6"    
[33] "C7"     "C8"     "C9"     "C10"    "C11"    "C12"    "D1"     "D2"    
[41] "D3"     "D4"     "D5"     "D6"     "D7"     "D8"     "D9"     "D10"   
[49] "D11"    "D12"    "E1"     "E2"     "E3"     "E4"     "E5"     "E6"    
[57] "E7"     "E8"     "E9"     "E10"    "E11"    "E12"    "F1"     "F2"    
[65] "F3"     "F4"     "F5"     "F6"     "F7"     "F8"     "F9"     "F10"   
[73] "F11"    "F12"    "G1"     "G2"     "G3"     "G4"     "G5"     "G6"    
[81] "G7"     "G8"     "G9"     "G10"    "G11"    "G12"    "H1"     "H2"    
[89] "H3"     "H4"     "H5"     "H6"     "H7"     "H8"     "H9"     "H10"   
[97] "H11"    "H12"   </code></pre>
</div>
</div>
<p>The layout is the same as PB9 strain, with time, temperature and well columns.</p>
<p><strong>Removing Temp column, check for NAs and 49 time points:</strong>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>MG1655_gc <span class="ot">&lt;-</span> MG1655_gc[,<span class="sc">-</span><span class="dv">2</span>] <span class="co">#remove Temp column because it's useless</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">checklength_and_NAs</span>(MG1655_gc) <span class="co">#no NAs, all columns are 49 timepoints.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>All good.</p>
<p><strong>Make newtime column, make long formatted table so it is tidy, and make ‘column’ and ‘row’ columns:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>MG1655_gc <span class="ot">&lt;-</span> <span class="fu">makenewtime</span>(MG1655_gc)  <span class="co">#make newtime column</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>MG1655_gc <span class="ot">&lt;-</span> <span class="fu">pivotlong_gc</span>(MG1655_gc) <span class="co">#pivot longer</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  Time   newtime well  OD600
  &lt;time&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
1 00'00"       0 A1    0.154
2 00'00"       0 A2    0.165
3 00'00"       0 A3    0.155
[1] "nrow:  4704"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>MG1655_gc <span class="ot">&lt;-</span> <span class="fu">addcolumnrow</span>(MG1655_gc) <span class="co">#add column and row columns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  Time   newtime well  OD600 row   column
  &lt;time&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;fct&gt; 
1 00'00"       0 A1    0.154 A     1     
2 00'00"       0 A2    0.165 A     2     
3 00'00"       0 A3    0.155 A     3     </code></pre>
</div>
</div>
<p><strong>Read in the drug concentrations for this file</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>MG1655drugconcs <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"drugconcs/MG1655_drugconcs.csv"</span>, <span class="at">show_col_types =</span> F) <span class="co">#read in drug concs</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(MG1655drugconcs) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  ampconc_ugml pepconc_ugml ampconc_uM pepconc_uM
         &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
1            0           NA          0         NA
2            1            0          3          0
3            2           18          5         10
4            4           36         11         20
5            6           45         16         25
6            8           53         22         30</code></pre>
</div>
</div>
<p>There are more NAs, this is because I did not use the first column and last column on the 96-well plate when I was doing the checkerboard. I will need to remove these NAs later. Later I need to repeat this experiment and do a full control using all wells.</p>
<p><strong>Add drug concs to the main MG1655 growth curve data frame:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>MG1655_gc <span class="ot">&lt;-</span> <span class="fu">adddrugconcs</span>(MG1655_gc, MG1655drugconcs)  <span class="co">#looks good.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 8
  Time   newtime well  OD600 row   column amp_uM pep_uM
  &lt;time&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt;  &lt;fct&gt; 
1 00'00"       0 A1    0.154 A     1      0      &lt;NA&gt;  
2 00'00"       0 A2    0.165 A     2      0      0     
3 00'00"       0 A3    0.155 A     3      0      10    </code></pre>
</div>
</div>
<p><strong>Subtract background OD600:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>MG1655_gc<span class="sc">$</span>OD600 <span class="ot">&lt;-</span> MG1655_gc<span class="sc">$</span>OD600 <span class="sc">-</span> bgOD<span class="sc">$</span>OD600</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(MG1655_gc<span class="sc">$</span>OD600) <span class="co">#looks good (a little below 0 is fine)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.013  1.091</code></pre>
</div>
</div>
<p><strong>Now we can remove the rows containing NAs</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>MG1655_gc <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(MG1655_gc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Make control row and control column plots:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">makesinglerowplotamp</span>(MG1655_gc, </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">title =</span> <span class="st">"24h growth curve of E.coli MG1655 control strain </span><span class="sc">\n</span><span class="st">treated without peptide"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment6_markdown_JohannaEnright_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>MG16155 is responding as expected to ampicillin, with higher concentrations of drug resulting in less growth.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">makesinglerowplotpep</span>(MG1655_gc,</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">title =</span> <span class="st">"24h growth curve of E.coli MG1655 control strain </span><span class="sc">\n</span><span class="st">treated without ampicillin"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment6_markdown_JohannaEnright_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I think this looks good. Regardless of the peptide concentration, the wells pretty much grow the same. This makes sense as there is no TEM-1 for the peptide to inhibit. Interesting that peptide only appeared to have an effect in the PB9 test strain but not in the control strain.</p>
</section>
<section id="growth-curves-for-mg1655-checkerboard." class="level4">
<h4 class="anchored" data-anchor-id="growth-curves-for-mg1655-checkerboard.">Growth Curves for MG1655 Checkerboard.</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>MG1655plot <span class="ot">&lt;-</span> <span class="fu">make_allwellgc</span>(MG1655_gc,</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">title =</span> <span class="st">"24h Growth curve of Checkerboard assay for MG1655 control strain."</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave2</span>(<span class="at">plot =</span> MG1655plot, <span class="at">filename =</span> <span class="st">"plots/MG1655_allwellplot.jpeg"</span>,  <span class="at">width =</span> <span class="dv">24</span>, <span class="at">height =</span> <span class="dv">16</span>, <span class="at">units =</span> <span class="st">"cm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="plots/MG1655_allwellplot.jpeg" class="img-fluid"> This one appears pretty consistent across the x axis, meaning the peptide is having little effect on growth (this is what we expect.) Growth is inhibited at 11-16<span class="math inline">\(\mu M\)</span> of ampicillin which is a low amount that we would expect for a non-resistant strain of bacteria. The jagged growth in well D6 appears to be just noise, but a replicate plate will need to be run anyways.</p>
</section>
<section id="doing-auc-analyses-for-mg1655" class="level4">
<h4 class="anchored" data-anchor-id="doing-auc-analyses-for-mg1655">Doing AUC Analyses for MG1655</h4>
<p><strong>Calculating AUC and adding to growth curve data</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>wellnums <span class="ot">&lt;-</span> <span class="fu">unique</span>(MG1655_gc<span class="sc">$</span>well)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>MG1655areas <span class="ot">&lt;-</span> <span class="fu">areavector</span>(MG1655_gc)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>MG1655areas </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 13.54 12.78 12.12 12.25 12.24 11.59 11.96 11.31 12.00 15.60 12.07 10.88
[13] 10.55  9.61  9.44 10.07 10.60  8.76 13.59 10.19  6.19  6.59  4.54  5.28
[25]  5.21  4.91  4.84  8.38  5.30 12.59  1.51  2.21  1.57 11.06  1.66 15.48
[37]  0.36  2.01  0.86  0.66  0.06  0.28  0.19  0.31  0.39  0.29  0.33  1.44
[49]  0.58  0.66  0.11  0.15  0.16  0.33  0.25  0.36  0.75  0.44  0.54  0.87
[61]  0.19  0.15  0.21  0.21  0.23  0.30  0.45  0.54  0.69  0.90 -0.10  0.16
[73]  0.17  0.21  0.23  0.96  0.39  0.51  2.05  0.83</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(MG1655areas) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 80</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(MG1655areas)  <span class="co">#this all looks good.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1 15.6</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>MG1655_gc <span class="ot">&lt;-</span> MG1655_gc <span class="sc">%&gt;%</span>  <span class="fu">mutate</span>(<span class="at">area =</span> <span class="fu">rep</span>(MG1655areas, <span class="dv">49</span>))   <span class="co">#adding area to df</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>MG1655_gc <span class="sc">%&gt;%</span> <span class="fu">head</span>()  <span class="co">#looks good</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  Time   newtime well  OD600 row   column amp_uM pep_uM  area
  &lt;time&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;fct&gt;  &lt;fct&gt;  &lt;fct&gt;  &lt;dbl&gt;
1 00'00"       0 A2    0.072 A     2      0      0       13.5
2 00'00"       0 A3    0.061 A     3      0      10      12.8
3 00'00"       0 A4    0.025 A     4      0      20      12.1
4 00'00"       0 A5    0.023 A     5      0      25      12.2
5 00'00"       0 A6    0.098 A     6      0      30      12.2
6 00'00"       0 A7    0.084 A     7      0      35      11.6</code></pre>
</div>
</div>
<p>looks good.</p>
<p><strong>Make Heat Map for MG1655</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>MG1655_hmap <span class="ot">&lt;-</span> <span class="fu">makeheatmap</span>(MG1655_gc, </span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">title =</span> <span class="st">"Heatmap of area under the curve </span><span class="sc">\n</span><span class="st">for each well in Checkerboard for MG1655 E.coli"</span>) </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave2</span>(<span class="at">plot =</span> MG1655_hmap, <span class="at">filename =</span> <span class="st">"plots/MG1655_hmap.jpeg"</span>, <span class="at">width =</span> <span class="dv">12</span>, <span class="at">height =</span> <span class="dv">8</span>, <span class="at">units =</span> <span class="st">"cm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="plots/MG1655_hmap.jpeg" class="img-fluid" style="width:8in"> Overall, this supports the growth curve plot results that MG1655 is working expected as a control and that the peptide inhibits TEM-1 which is why there is no peptide effect on MG1655.</p>
</section>
<section id="comparing-the-pb9-and-mg1655-plots-side-by-side" class="level4">
<h4 class="anchored" data-anchor-id="comparing-the-pb9-and-mg1655-plots-side-by-side">Comparing the PB9 and MG1655 Plots Side by Side</h4>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="plots/MG1655_allwellplot.jpeg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="plots/PB9_allwellplot.jpeg" class="img-fluid"></p>
</div>
</div>
</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="plots/MG1655_hmap.jpeg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="plots/PB9_hmap.jpeg" class="img-fluid"></p>
</div>
</div>
</div>
<p>Overall, for the TEM-1 containing strain, the peptide when combined with the ampicillin does seem to inhibit growth more than either drug alone as demonstrated by lower AUC at higher peptide concentration (when paired with amp.) This combined with the MG1655 control data which does not seem to respond to the peptide supports the claim that the peptide is in fact able to bind and inhibit TEM-1 in the PB9 test strain. Of course more testing on different strains with multiple replicates will need to be done, and statistical analyses performed before any conclusions can be drawn.</p>
<p>THE END :)</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>
